---
sidebar: sidebar 
permalink: reference-provider-integrations.html 
keywords: maintenance event, azure maintenance event, cloud provider, issues, support 
summary: 此页面介绍了 NetApp 如何与云提供商合作来解决可能出现的问题。 
---
= 云提供商集成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
此页面介绍了 NetApp 如何与云提供商合作来解决可能出现的问题。



== 协作支持最佳实践

NetApp 承诺为被许可方提供支持，并在被许可方报告情况下，尽商业上合理的努力解决 Cloud Volumes ONTAP 的技术支持问题。NetApp 和适用的云提供商对彼此的许可软件或基础架构不承担任何直接支持义务。

NetApp 实施了一些工具，旨在就可能因适用的云提供商服务而导致的客户技术问题与适用的云提供商建立联系。但是， 保持无缝支持流的最佳方式是：（ i ）与 NetApp 和适用的云提供商保持最新的支持合同；（ ii ）在出现技术问题且客户需要明确说明时，与 NetApp 和适用的云提供商协调联合上报会议 导致这些技术问题的产品或服务。



== Azure 维护事件

Microsoft 在其 Azure 虚拟机（ VM ）基础架构上计划并以编程方式宣布可能影响 Cloud Volumes ONTAP VM 的维护事件。这些事件会在维护窗口的 15 分钟前公布。

Cloud Volumes ONTAP 高可用性（ HA ）对支持特殊处理维护事件。为了保持应用程序运行状况，我们会执行预防性接管以确定稳定性的优先级，因为任何连接断开超过 15 秒将禁用故障转移功能。

宣布维护窗口后，目标节点的配对节点将执行接管。维护完成后，将启动交还。交还后， HA 对应恢复为运行状况良好的状态。如果未发生这种情况，请联系 NetApp 支持部门以获得帮助。请注意，维护事件一次针对 HA 对中的一个虚拟机，通常这两个节点都是在相对较短的时间内针对的。

使用 Cloud Volumes ONTAP 非持续可用的 CIFS 共享的 CIFS/SMB 客户端将在发生接管时以及将会话所使用的聚合交还给聚合的主节点时丢失会话。这是 CIFS/SMB 协议本身施加的限制。客户可能希望使用第三方产品来避免因接管和交还而可能出现的问题。要获得更多帮助，请联系 NetApp 支持部门。
