---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, detaching, snapmanager, features, disks, aggregates, features, svm 
summary: 已知限制确定了本产品版本不支持的平台、设备或功能、或者这些平台、设备或功能无法与产品正确交互操作。仔细审查这些限制。 
---
= 所有云提供商的限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制确定了本产品版本不支持的平台、设备或功能、或者这些平台、设备或功能无法与产品正确交互操作。仔细审查这些限制。

以下限制适用于所有云提供商中的 Cloud Volumes ONTAP ： AWS ， Azure 和 Google Cloud 。



== 最大并发复制操作数

无论实例类型或计算机类型如何， Cloud Volumes ONTAP 的并发 SnapMirror 或 SnapVault 传输的最大数量均为每个节点 100 。



== 您的备份和恢复计划不得使用云提供商快照

您不应在 Cloud Volumes ONTAP 数据的备份和恢复计划中使用云提供商的快照。您应始终使用 ONTAP Snapshot 副本或第三方备份解决方案备份和还原 Cloud Volumes ONTAP 上托管的数据。

https://docs.netapp.com/us-en/cloud-manager-backup-restore/concept-backup-to-cloud.html["了解如何使用 Cloud Backup Service 备份和还原 ONTAP 数据"^]。


NOTE: WAFL 文件系统中的 ONTAP 一致性点决定了数据一致性。只有 ONTAP 可以暂停 WAFL 文件系统以进行崩溃状态一致的备份。



== 在中国地区提供支持

中国地区支持 Cloud Volumes ONTAP ，如下所示。

* AWS 中国地区支持 Cloud Volumes ONTAP 9.6 。
* 支持单节点系统。
* 支持直接从 NetApp 购买的许可证。


不支持所有其他位置，版本，配置和许可证。



== Cloud Volumes ONTAP 支持预留和按需 VM 实例

Cloud Volumes ONTAP 可以在云提供商提供的预留或按需 VM 实例上运行。不支持其他类型的 VM 实例。



== 不应使用自动应用程序资源管理解决方案

自动应用程序资源管理解决方案不应管理 Cloud Volumes ONTAP 系统。这样做可能会导致更改不受支持的配置。例如，解决方案可能会将 Cloud Volumes ONTAP 更改为不受支持的 VM 实例类型。



== 软件更新必须由 Cloud Manager 完成

Cloud Volumes ONTAP 升级必须从 Cloud Manager 完成。您不应使用 System Manager 或命令行界面升级 Cloud Volumes ONTAP 。这样做可能会影响系统稳定性。



== 不得从云提供商的控制台修改 Cloud Volumes ONTAP 部署

通过云提供商的控制台更改 Cloud Volumes ONTAP 配置会导致配置不受支持。对 Cloud Manager 创建和管理的 Cloud Volumes ONTAP 资源进行的任何更改都会影响系统稳定性以及 Cloud Manager 管理系统的能力。



== 磁盘和聚合必须通过 Cloud Manager 进行管理

必须直接从 Cloud Manager 创建和删除所有磁盘和聚合。不应从其他管理工具执行这些操作。这样做可能会影响系统稳定性、妨碍将来添加磁盘的能力、并可能产生冗余云提供商费用。



== SnapManager 许可限制

Cloud Volumes ONTAP 支持 SnapManager 每服务器许可证。不支持每存储系统（ SnapManager 套件）许可证。



== 不支持的 ONTAP 功能

Cloud Volumes ONTAP 不支持以下功能：

* 聚合级实时重复数据删除
* 聚合级后台重复数据删除
* 磁盘维护中心
* 磁盘清理
* FabricPool 镜像
* 光纤通道（ FC ）
* Flash Pool
* 无限卷
* 接口组
* 索引节点 LIF 故障转移
* MetroCluster
* Google Cloud中的ONTAP S3 (Azure和AWS支持S3协议)
* RAID4 ， RAID-DP ， RAID-TEC （支持 RAID0 ）
* 服务处理器
* SnapLock 合规性和企业模式（仅支持 Cloud WORM ）
* SnapMirror 同步
* VLAN

