---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: Cloud Volumes ONTAP 在 Google Cloud 中设置了存储配置限制，以提供可靠的操作。为获得最佳性能，请勿将系统配置为最大值。 
---
= Google Cloud 中的存储限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 具有存储配置限制，可提供可靠的操作。为获得最佳性能，请勿将系统配置为最大值。



== 按许可证计算的最大系统容量

Cloud Volumes ONTAP 系统的最大系统容量取决于其许可证。最大系统容量包括基于磁盘的存储以及用于数据分层的对象存储。

NetApp 不支持超过系统容量限制。如果您达到许可的容量限制， Cloud Manager 将显示一条需要执行操作消息，并且不再允许您添加其他磁盘。

对于某些配置，磁盘限制会阻止您单独使用磁盘来达到容量限制。您可以通过达到容量限制 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["将非活动数据分层到对象存储"^]。有关详细信息，请参见以下磁盘限制。

[cols="25,75"]
|===
| 许可证 | 最大系统容量（磁盘 + 对象存储） 


| 免费 | 500 GB 


| PAYGO 探索 | 2 TB （ Explore 不支持数据分层） 


| PAYGO 标准 | 10 TB 


| PAYGO 高级版 | 368 TB 


| 基于节点的许可证 | 每个许可证 368 TB 


| 基于容量的许可证 | 2 个 PIB 
|===
容量限制适用于整个 HA 对。不是每个节点。例如，如果使用高级版许可证，则两个节点之间的容量最多可达 368 TB 。

不可以。HA 对中的数据会在节点之间同步镜像，以便在 Google Cloud 发生故障时可以使用这些数据。例如，如果您在节点 A 上购买了 8 TB 磁盘，则 Cloud Manager 还会在节点 B 上分配一个 8 TB 磁盘，用于镜像数据。虽然配置了 16 TB 的容量，但许可证限制仅会计入 8 TB 的容量。



== 聚合限制

Cloud Volumes ONTAP 将 Google 云平台磁盘分组为 _aggreges_ 。聚合可为卷提供存储。

[cols="2*"]
|===
| 参数 | limit 


| 最大数据聚合数 ^1^  a| 
* 99 表示单个节点
* 64 表示整个 HA 对




| 最大聚合大小 | 256 TB 原始容量 ^2^ 


| 每个聚合的磁盘数 | 1-6 ^3^ 


| 每个聚合的最大 RAID 组数 | 1. 
|===
注释：

. 数据聚合的最大数量不包括根聚合。
. 聚合容量限制基于构成聚合的磁盘。此限制不包括用于数据分层的对象存储。
. 聚合中的所有磁盘大小必须相同。




== 磁盘和分层限制

下表显示了单独使用磁盘以及将磁盘和冷数据分层到对象存储的最大系统容量。磁盘限制特定于包含用户数据的磁盘。限制不包括启动磁盘、根磁盘或NVRAM。

[cols="60,40"]
|===
| 参数 | limit 


| 最大数据磁盘数  a| 
* 124 ，用于单节点系统
* 对于 HA 对，每个节点 123 个




| 最大磁盘大小 | 64 TB 


| 仅使用磁盘时的最大系统容量 | 256 TB ^1^ 


| 将磁盘和冷数据分层到 Google Cloud 存储分段时的最大系统容量 | 取决于许可证。请参见上述最大系统容量限制。 
|===
^1^ 此限制由 Google Cloud Platform 中的虚拟机限制定义。



== Storage VM 限制

在某些配置中，您可以为 Cloud Volumes ONTAP 创建其他 Storage VM （ SVM ）。

这些是经过测试的限制。虽然理论上可以配置其他 Storage VM ，但不支持。

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-managing-svms-gcp.html["了解如何创建其他 Storage VM"^]。

[cols="2*"]
|===
| 许可证类型 | Storage VM 限制 


| * 免费 *  a| 
共24个Storage VM ^1^



| *基于容量的PAYGO或BYOL*^2^  a| 
共24个Storage VM ^1^



| *基于节点的BYOL*^3^  a| 
共24个Storage VM ^1^



| * 基于节点的 PAYGO*  a| 
* 1 个存储 VM 用于提供数据
* 1 个 Storage VM 用于灾难恢复


|===
. 这 24 个 Storage VM 可以提供数据或配置为灾难恢复（ Disaster Recovery ， DR ）。
. 对于基于容量的许可，额外的 Storage VM 不会产生额外的许可成本，但每个 Storage VM 的最低容量费用为 4 TiB 。例如，如果您创建了两个 Storage VM ，并且每个 VM 都有 2 TiB 的已配置容量，则总共需要支付 8 TiB 的费用。
. 对于基于节点的 BYOL ，除了默认情况下随 Cloud Volumes ONTAP 提供的第一个 Storage VM 之外，每个额外的 _data-fouring 存储 VM 都需要一个附加许可证。请联系您的客户团队以获取 Storage VM 附加许可证。
+
您为灾难恢复（ DR ）配置的 Storage VM 不需要附加许可证（它们是免费的），但它们会计入 Storage VM 限制。例如，如果为灾难恢复配置了 12 个提供数据的 Storage VM 和 12 个 Storage VM ，则表示已达到此限制，无法再创建任何 Storage VM 。





== 逻辑存储限制

[cols="22,22,56"]
|===
| 逻辑存储 | 参数 | limit 


.2+| * 文件 * | 最大大小 | 16 TB 


| 每个卷的上限 | 取决于卷大小，最多 20 亿个 


| * FlexClone 卷 * | 分层克隆深度^12^ | 499 


.3+| * FlexVol 卷 * | 每个节点的上限 | 500 


| 最小大小 | 20 MB 


| 最大大小 | 100 TB 


| * qtree* | 每个 FlexVol 卷的上限 | 4,995 


| * Snapshot 副本 * | 每个 FlexVol 卷的上限 | 1,023 
|===
. 分层克隆深度是可以从单个 FlexVol 卷创建的 FlexClone 卷嵌套层次结构的最大深度。




== iSCSI 存储限制

[cols="3*"]
|===
| iSCSI 存储 | 参数 | limit 


.4+| * LUN * | 每个节点的上限 | 1,024 


| LUN 映射的最大数量 | 1,024 


| 最大大小 | 16 TB 


| 每个卷的上限 | 512 


| * igroup* | 每个节点的上限 | 256 


.2+| * 启动程序 * | 每个节点的上限 | 512 


| 每个 igroup 的最大值 | 128. 


| * iSCSI 会话 * | 每个节点的上限 | 1,024 


.2+| * LIF* | 每个端口的上限 | 1. 


| 每个端口集的最大值 | 32 


| * 端口集 * | 每个节点的上限 | 256 
|===