---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.12.1提供了一项新的增强功能。 
---
= Cloud Volumes ONTAP 9.12.1中的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.12.1提供了新的增强功能。

最新版本的BlueXP (以前称为Cloud Manager)还引入了其他功能和增强功能。请参见 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["《BlueXP发行说明》"^] 了解详细信息。



== 9.12.1 RC1 (2022年12月8日)

Cloud Volumes ONTAP 9.12.1候选版本1现已在AWS、Azure和Google Cloud中推出。此版本包含以下新增功能和增强功能：



=== 支持的升级路径

您可以从9.12.0版和9.11.1版升级到Cloud Volumes ONTAP 9.12.1。BlueXP将提示您将符合条件的Cloud Volumes ONTAP 系统升级到此版本。



=== 所需版本的Connector

要部署新的Cloud Volumes ONTAP 9.12.1系统并将现有系统升级到9.12.1、BlueXP连接器必须运行版本3.9.23或更高版本。


TIP: 默认情况下，连接器会自动升级，因此您应运行最新版本。



=== GCP中的ONTAP S3许可证

现在、在Google云平台中运行9.12.1或更高版本的新Cloud Volumes ONTAP 系统和现有系统上均包含ONTAP S3许可证。

https://docs.netapp.com/us-en/ontap/object-storage-management/index.html["了解如何在 ONTAP 中配置和管理 S3 对象存储服务"^]



=== Cloud Volumes ONTAP 中支持NVMe-TCP

如果您使用的是Cloud Volumes ONTAP 9.12.1或更高版本、则云提供商支持NVMe-TCP。BlueXP不为NVMe-TCP提供任何管理功能。

有关通过ONTAP 配置NVMe的详细信息、请参见 link:https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-nvme-task.html["为NVMe配置Storage VM"^]。



=== Azure HA位于具有共享受管磁盘的单个可用性区域中

现在、您可以使用在共享受管磁盘上运行的Microsoft Azure本地冗余存储(LRS)部署Cloud Volumes ONTAP HA配置。本地冗余存储可在同一区域的单个数据中心内复制三次数据。

有关HA配置架构和组件的详细信息、请参见 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-azure.html["Azure 中的高可用性对"^]。

在一个可用性区域中的Azure中部署新HA对时、您现在将使用LRS共享受管磁盘、而不是页面Blobs进行存储。"工作环境"向导未发生任何更改。要使用此新配置、只需选择一个可用性区域即可。有关详细信息，请参见 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-azure.html["在Azure中启动Cloud Volumes ONTAP HA对"^]。



=== 使用共享受管磁盘在多个可用性区域中配置Azure HA

现在、您可以使用Azure在一个区域中部署多个可用性区域来部署Cloud Volumes ONTAP HA配置。这种新配置可通过使用Azure分区冗余存储(ZRS)共享受管磁盘来防止数据中心故障并保持应用程序可用性。

有关HA配置架构和组件的详细信息、请参见 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-ha-azure.html["Azure 中的高可用性对"^]。

要使用此新配置、请参见 link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-deploying-otc-azure.html["在Azure中启动Cloud Volumes ONTAP HA对"^]。



== 不再支持c4、m4和r4实例(2022年10月28日)

在AWS中、Cloud Volumes ONTAP 不再支持C4、M4和M4 EC2实例类型。如果现有系统运行的是C4、M4或r4实例类型、则必须更改为c5、M5或R5实例系列中的实例类型。

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["了解如何更改Cloud Volumes ONTAP 的EC2实例类型"^]。

请参见 link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp 支持"^] 了解有关这些实例类型的可用性和支持终止的更多信息。
