---
sidebar: sidebar 
permalink: reference-limits-gcp.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM 
summary: Cloud Volumes ONTAP 在 Google Cloud 中设置了存储配置限制，以提供可靠的操作。为获得最佳性能，请勿将系统配置为最大值。 
---
= Cloud Volumes ONTAP在Google Cloud中的存储限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 具有存储配置限制，可提供可靠的操作。为获得最佳性能，请勿将系统配置为最大值。



== 按许可证计算的最大系统容量

Cloud Volumes ONTAP 系统的最大系统容量取决于其许可证。最大系统容量包括基于磁盘的存储以及用于数据分层的对象存储。

NetApp 不支持超过系统容量限制。如果您达到许可的容量限制、BlueXP将显示一条需要执行操作消息、并且不再允许您添加其他磁盘。

对于某些配置，磁盘限制会阻止您单独使用磁盘来达到容量限制。您可以通过达到容量限制 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["将非活动数据分层到对象存储"^]。有关详细信息，请参见以下磁盘限制。

.基于容量的许可证的容量限制
通过基于容量的许可，每个Cloud Volumes ONTAP系统都支持分层到对象存储。总分层容量可以扩展到云提供商的存储桶限制。虽然许可证没有施加容量限制，但您应该遵循 https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool最佳实践"^]确保在配置和管理分层时实现最佳性能、可靠性和成本效率。请参阅 https://cloud.google.com/storage/docs/buckets["Google Cloud 文档"^]了解更多信息。

其他许可证类型的容量限制::


[cols="25,75"]
|===
| 许可证 | 最大系统容量（磁盘 + 对象存储） 


| 免费 | 500 GB 


| PAYGO 探索 | 2 TB （ Explore 不支持数据分层） 


| PAYGO 标准 | 10 TB 


| PAYGO 高级版 | 368 TB 


| 基于节点的许可证 | 2 PIB (需要多个许可证) 
|===
.对于 HA 对，是每个节点的许可容量限制还是整个 HA 对的许可容量限制？
容量限制适用于整个 HA 对。不是每个节点。例如，如果使用高级版许可证，则两个节点之间的容量最多可达 368 TB 。

.对于 HA 对，镜像数据是否计入许可的容量限制？
不，不是这样的。 HA 对中的数据在节点之间同步镜像，以便在 Google Cloud 发生故障时数据可用。例如，如果您在节点 A 上购买了 8 TB 磁盘， BlueXP还会在节点 B 上分配一个 8 TB 磁盘用于镜像数据。虽然设置了 16 TB 的容量，但只有 8 TB 计入许可证限制。



== 聚合限制

Cloud Volumes ONTAP 将 Google 云平台磁盘分组为 _aggreges_ 。聚合可为卷提供存储。

[cols="2*"]
|===
| 参数 | limit 


| 最大数据聚合数 ^1^  a| 
* 99 表示单个节点
* 64 表示整个 HA 对




| 最大聚合大小 | 256 TB 原始容量 ^2^ 


| 每个聚合的磁盘数 | 1-6 ^3^ 


| 每个聚合的最大 RAID 组数 | 1. 
|===
注释：

. 数据聚合的最大数量不包括根聚合。
. 组成聚合的磁盘决定了聚合容量限制。此限制不包括用于数据分层的对象存储。
. 聚合中的所有磁盘大小必须相同。




== 磁盘和分层限制

下表显示了单独使用磁盘以及将磁盘和冷数据分层到对象存储的最大系统容量。磁盘限制特定于包含用户数据的磁盘。限制不包括启动磁盘、根磁盘或NVRAM。

[cols="60,40"]
|===
| 参数 | limit 


| 最大数据磁盘数  a| 
* 124 ，用于单节点系统
* 对于 HA 对，每个节点 123 个




| 最大磁盘大小 | 64 TB 


| 仅使用磁盘时的最大系统容量 | 256 TB ^1^ 


| 将磁盘和冷数据分层到 Google Cloud 存储分段时的最大系统容量 | 取决于许可证。请参见上述最大系统容量限制。 
|===
^1^ 此限制由 Google Cloud Platform 中的虚拟机限制定义。



== Storage VM 限制

在某些配置中，您可以为 Cloud Volumes ONTAP 创建其他 Storage VM （ SVM ）。

这些是经过测试的极限。不支持配置更多存储虚拟机。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-managing-svms-gcp.html["了解如何创建其他 Storage VM"^]。

[cols="2*"]
|===
| 许可证类型 | Storage VM 限制 


| * 免费 *  a| 
共24个Storage VM ^1^



| *基于容量的PAYGO或BYOL*^2^  a| 
共24个Storage VM ^1^



| *基于节点的BYOL*^3^  a| 
共24个Storage VM ^1^



| * 基于节点的 PAYGO*  a| 
* 1 个存储 VM 用于提供数据
* 1 个 Storage VM 用于灾难恢复


|===
. 这 24 个 Storage VM 可以提供数据或配置为灾难恢复（ Disaster Recovery ， DR ）。
. 对于基于容量的许可，额外的 Storage VM 不会产生额外的许可成本，但每个 Storage VM 的最低容量费用为 4 TiB 。例如，如果您创建了两个 Storage VM ，并且每个 VM 都有 2 TiB 的已配置容量，则总共需要支付 8 TiB 的费用。
. 对于基于节点的 BYOL，除了默认随Cloud Volumes ONTAP附带的第一个存储虚拟机之外，每个额外的_数据服务_存储虚拟机都需要附加许可证。联系您的客户团队以获取存储 VM 附加许可证。
+
您为灾难恢复（ DR ）配置的 Storage VM 不需要附加许可证（它们是免费的），但它们会计入 Storage VM 限制。例如，如果为灾难恢复配置了 12 个提供数据的 Storage VM 和 12 个 Storage VM ，则表示已达到此限制，无法再创建任何 Storage VM 。





== 逻辑存储限制

[cols="22,22,56"]
|===
| 逻辑存储 | 参数 | limit 


.2+| * 文件 * | 最大尺寸^2^ | 128 TB 


| 每个卷的上限 | 取决于卷大小，最多 20 亿个 


| * FlexClone 卷 * | 分层克隆深度^12^ | 499 


.3+| * FlexVol 卷 * | 每个节点的上限 | 500 


| 最小大小 | 20 MB 


| 最大尺寸^3^ | 300 TiB 


| * qtree* | 每个 FlexVol 卷的上限 | 4,995 


| * Snapshot 副本 * | 每个 FlexVol 卷的上限 | 1,023 
|===
. 分层克隆深度是可以从单个 FlexVol 卷创建的 FlexClone 卷嵌套层次结构的最大深度。
. 从ONTAP 9.12.1P2开始、此限制为128 TB。在ONTAP 9.11.1及更早版本中、此限制为16 TB。
. 支持使用以下工具和最低版本创建最大大小为300 TiB的FlexVol卷：
+
** Cloud Volumes ONTAP 9.12.1 P2和9.13.0 P2开始的System Manager和ONTAP命令行界面
** 从Cloud Volumes ONTAP 9.13.1.开始的BlueXP






== iSCSI 存储限制

[cols="3*"]
|===
| iSCSI 存储 | 参数 | limit 


.4+| * LUN * | 每个节点的上限 | 1,024 


| LUN 映射的最大数量 | 1,024 


| 最大大小 | 16 TB 


| 每个卷的上限 | 512 


| * igroup* | 每个节点的上限 | 256 


.2+| * 启动程序 * | 每个节点的上限 | 512 


| 每个 igroup 的最大值 | 128. 


| * iSCSI 会话 * | 每个节点的上限 | 1,024 


.2+| * LIF* | 每个端口的上限 | 1. 


| 每个端口集的最大值 | 32 


| * 端口集 * | 每个节点的上限 | 256 
|===


== Cloud Volumes ONTAP HA 对不支持即时存储交还

节点重新启动后，配对节点必须先同步数据，然后才能返回存储。重新同步数据所需的时间取决于节点关闭时客户端写入的数据量以及交还期间的数据写入速度。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha-google-cloud.html["了解存储如何在Google Cloud中运行的Cloud Volumes ONTAP HA对中工作"^]。
