---
sidebar: sidebar 
permalink: reference-limitations-azure.html 
keywords: limitations, ha, azure, pay-as-you-go, paygo, cloud solution provider, vm, flash cache 
summary: 这些已知限制特定于 Microsoft Azure 中的 Cloud Volumes ONTAP 。 
---
= Azure中Cloud Volumes ONTAP的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
以下已知限制特定于 Microsoft Azure 中的 Cloud Volumes ONTAP 。请务必同时查看 link:reference-limitations.html["所有云提供商中 Cloud Volumes ONTAP 的限制"]。



== 使用Azure VM扩展的限制

Cloud Volumes ONTAP不支持 Azure 虚拟机 (VM) 扩展，因为它们会影响BlueXP管理操作。在部署期间， BlueXP会阻止在您的虚拟机上安装任何扩展。如果您现有的Cloud Volumes ONTAP虚拟机上已安装扩展， NetApp强烈建议您联系 Microsoft Azure 支持部门将其删除。

从 2025 年 7 月 14 日开始，如果在您的Cloud Volumes ONTAP VM 上检测到 VM 扩展， NetApp将在BlueXP中通知您并发送电子邮件。



== Flash Cache 限制

在某些虚拟机类型中、Cloud Volumes ONTAP会将本地NVMe存储用作_Flash Cache _。请注意以下限制：

* 不支持在重新启动后重新恢复缓存。




== 高可用性部署的限制

某些地区不支持高可用性(HA)对。

https://bluexp.netapp.com/cloud-volumes-global-regions["查看支持的 Azure 区域列表"^](英文)



== 在单个可用性区域中进行HA部署的限制

从Cloud Volumes ONTAP 9.15.1开始、您可以在Azure的单可用性区域(Single Availability Zones、AZs)中以HA模式部署虚拟机(VM)实例。有关支持此功能的标准的信息，请参见 https://docs.netapp.com/us-en/cloud-volumes-ontap-9151-relnotes/reference-new.html#deploy-ha-pairs-in-single-availability-zones-on-azure["在Azure的单个可用性区域中部署HA对"^]。

如果Cloud Volumes ONTAP版本为早期版本的9.15.1、或者不满足其中任何一个条件、则使用可用性集的先前部署模式将生效。这仅适用于HA配置。
