---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.13.0提供了一项新的增强功能。 
---
= Cloud Volumes ONTAP 9.13.0中的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.13.0提供了新的增强功能。

最新版本的BlueXP (以前称为Cloud Manager)还引入了其他功能和增强功能。请参见 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["《BlueXP发行说明》"^] 了解详细信息。



== 9.13.0 GA (2023年3月5日)

Cloud Volumes ONTAP 9.13.0的通用发布(GA)版本现在可在AWS、Azure和Google Cloud中使用。此版本包含以下新增功能和增强功能：



=== Google Cloud中的Flash Cache和高写入速度

现在、对于Cloud Volumes ONTAP 9.13.0版本的特定实例、可支持闪存、高写入速度和8、896字节的高最大传输单元(MTU)。

了解更多信息 link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["支持Google Cloud按许可证配置"^]。



=== Google Cloud中的映像验证

现在、我们提供了增强的安全功能来验证通过Google Cloud导出的Cloud Volumes ONTAP 映像文件的签名。

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-gcp-image-verification.html["了解有关Google Cloud映像验证的更多信息"^]。



=== Google Cloud中的新实例支持

现在、对于Cloud Volumes ONTAP 单节点部署和Google Cloud中的高可用性部署、Freemium、PAYGO Premium、基于节点的BYOL和基于容量的许可证支持两种新的实例类型。

* n2-standard-48
* n2-standard-64


link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["详细了解Google Cloud中支持的配置"^]。



== 升级说明

通读这些注释、了解有关升级到此版本的更多信息。



=== 如何升级

必须从BlueXP完成Cloud Volumes ONTAP 升级。您不应使用 System Manager 或命令行界面升级 Cloud Volumes ONTAP 。这样做可能会影响系统稳定性。

link:http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["了解在收到BlueXP通知时如何升级"^]。



=== 支持的升级路径

您可以从9.12.1版升级到Cloud Volumes ONTAP 9.13.0。BlueXP将提示您将符合条件的Cloud Volumes ONTAP 系统升级到此版本。



=== 所需版本的Connector

要部署新的Cloud Volumes ONTAP 9.13.0系统并将现有系统升级到9.13.0、BlueXP Connector必须运行版本3.9.26或更高版本。


TIP: 默认情况下，连接器会自动升级，因此您应运行最新版本。



=== 停机

* 升级单节点系统会使系统脱机长达 25 分钟，在此期间 I/O 会中断。
* 升级 HA 对无中断， I/O 不会中断。在此无中断升级过程中，每个节点会同时进行升级，以继续为客户端提供 I/O 。




=== 不再支持c4、m4和r4实例

在AWS中、Cloud Volumes ONTAP 不再支持C4、M4和M4 EC2实例类型。如果现有系统运行的是C4、M4或r4实例类型、则必须更改为c5、M5或R5实例系列中的实例类型。只有在更改实例类型后才能升级到此版本。

link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-change-ec2-instance.html["了解如何更改Cloud Volumes ONTAP 的EC2实例类型"^]。

请参见 link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["NetApp 支持"^] 了解有关这些实例类型的可用性和支持终止的更多信息。
